name: Issue report
description: Create a report to help us improve
title: "[ISSUE]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### Issue report form:

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: "Check before posting"
      options:
        - label: I have checked [__existing issues__](https://github.com/israpps/PlayStation2-Basic-BootLoader/issues) for duplicates and found none
        - label: I am using a build downloaded from [this repository](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases)

  - type: textarea
    id: explanation
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: My issue is...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Program setup
        > (please complete the following information):

  - type: input
    id: console
    attributes:
      label: Console model
      description: you can see it on the console sticker or inside OSDSYS (press triangle on main menu)
      placeholder: SCPH-????? | DTL-H????? | DESR-????
    validations:
      required: true

  - type: input
    id: oplver
    attributes:
      label: "Program version (if possible, also provide hash)"
      description: "you can see it on the program logo or by using the $CREDITS command"
      placeholder: "eg: v1.0.0 - beta. hash 41e4ebe"
    validations:
      required: true

  - type: dropdown
    id: changes
    attributes:
      label: "System modifications"
      description: "Aditional non-standard changes that are applied to the console"
      multiple: true
      options:
        - Modchip
        - MechaPWN
        - LensChanger

  - type: dropdown
    id: mode
    attributes:
      label: "What kind of boot method are you using to run the bootloader?"
      multiple: true
      options:
        - System Update
        - DEV1 / DEV2 / INFMAN
        - OpenTuna
        - Independence Exploit
        - HDD MBR
        - XFROM

  - type: textarea
    id: context-and-data
    attributes:
      label: Context and extra information
      description: Information about affected features and expected behavior
      placeholder: "running a game under x circumstances cause z issue."
    validations:
      required: false
