name: SIZE_TEST
#workflow that compares the different patches to reduce binary size, only runs if manually requested or each time a tagged relase is made
on:
  workflow_dispatch:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [
          DUMMY_LIBC_INIT=1, 
          DUMMY_TIMEZONE=1, 
          KERNEL_NOPATCH=1, 
          NEWLIB_NANO=1, 
          KERNEL_NOPATCH=1 NEWLIB_NANO=1,
          KERNEL_NOPATCH=1 NEWLIB_NANO=1 DUMMY_LIBC_INIT=1,
          KERNEL_NOPATCH=1 NEWLIB_NANO=1 DUMMY_TIMEZONE=1,  
          DEFAULT=1
          ]

    container: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base p7zip
    

    - name: Compile project
      run: |
        make release ${{ matrix.flags }}
        
    - name: repack project
      run: |
       7z a -t7z PS2BBL_${{ matrix.flags }}_.7z bin/*.ELF

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: PS2BBL_TEST_SIZE
        path: PS2BBL*.7z