name: CI

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths-ignore:
      - '**.MD'
      - '**.gitkeep'
      - '**.gitignore'

  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:

      - name: Install dependencies
        run: |
          apk add build-base git p7zip

      - uses: actions/checkout@v2
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Compile PS2 build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2/

      - name: list
        run: |
          git ls-files -i --exclude-standard -c

      - name: Compile PSX build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PSX/ PSX=1

      - name: list
        run: |
          git ls-files -i --exclude-standard -c

      - name: prepare release folder
        run: |
          cp $PS2SDK/iop/irx/usbd.irx release/PS2BBL/USBD.IRX
          cp $PS2SDK/iop/irx/bdm.irx release/PS2BBL/BDM.IRX
          cp $PS2SDK/iop/irx/bdmfs_fatfs.irx release/PS2BBL/BDMFS_FATFS.IRX
          cp $PS2SDK/iop/irx/usbmass_bd.irx release/PS2BBL/USBMASS_BD.IRX
          cp LICENSE release/LICENSE.TXT
          cp README.md release/README.md
          mv PS2/ release/PS2/
          mv PSX/ release/PSX/

      - name: pack release
        run: |
          CSH=${GITHUB_SHA::7}
          DATE=$(date "+%d-%m-%Y")
          TARGET="PS2BBL[$DATE]-[$CSH]"
          mv release/ $TARGET/
          7z a -t7z PS2BBL.7z $TARGET/*

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: PS2BBL
          path: |
            PS2BBL.7z

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            PS2BBL.7z
