name: CI

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
    paths:
      - '.github/workflows/CI.yml'
      - 'Makefile'
      - '*.make'
      - 'linkfile'
      - 'src/*'
      - 'include/*'
      - 'embed/*'
      - 'modules/*/*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:

      - name: Install dependencies
        run: |
          apk add build-base git zip

      - uses: actions/checkout@v2
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow
          sudo apt-get install --assume-yes p7zip-full 

      - name: Compile
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7}

      - name: list
        run: |
          git ls-files -i --exclude-standard -c

      - name: prepare release folder
        run: |
          cp $PS2SDK/iop/irx/usbd.irx release/PS2BBL/USBD.IRX
          cp $PS2SDK/iop/irx/bdm.irx release/PS2BBL/BDM.IRX
          cp $PS2SDK/iop/irx/bdmfs_fatfs.irx release/PS2BBL/BDMFS_FATFS.IRX
          cp $PS2SDK/iop/irx/usbmass_bd.irx release/PS2BBL/USBMASS_BD.IRX
          cp LICENSE release/LICENSE.TXT
          cp README.md release/README.md

      - name: pack release
        run: |
          CSH=${GITHUB_SHA::7}
          DATE=$(date "+%d-%m-%Y")
          TARGET="PS2BBL[$DATE]-[$CSH]"
          mv release/ $TARGET/
          7z a -t7z PS2BBL.7z $TARGET/*

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: PS2BBL
          path: |
            PS2BBL.7z

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            PS2BBL.7z
